name: HiWorldTech
author: [HiTech0926]
description: HiWorldTech Addon of A HiWorldServer
main: com.hitech0926.hiworldtech.HiWorldTech
website: https://addons.himcs.top
version: 1.0
api-version: 1.14
depend:
- Slimefun
